### PR TITLE
Refactor version and env indicator

### PR DESCRIPTION
**Pull request by qhantom**
## DESCRIPTION

This PR refactors the version and environment indicator. The version is now always shown inside the footer and derived from the project `package.json`.  The environment is implemented inside the runtime config and visualized inside the header component beside the theme switcher.

### TO-DO

- [x] implement and update tests
- [x] update docs
- [x] pull `main` & resolve merge conflicts
- [x] check Vercel deployment

### CLOSES

closes _list of issues closed in this PR_

### CODE REVIEW

**Review by PhilKsr — COMMENTED** [review]
Looks smooth, but I don't see any environment indicator. APP_ENV is set to development, seems to me like the runtimeConfig is not working as expected, since there are no changes on dev-server start.

**Comment by qhantom** [comment]
> Looks smooth, but I don't see any environment indicator. APP_ENV is set to development, seems to me like the runtimeConfig is not working as expected, since there are no changes on dev-server start.

Did you comment out the disable instrumentation env var in order to test it locally?

**Comment by PhilKsr** [comment]
> > Looks smooth, but I don't see any environment indicator. APP_ENV is set to development, seems to me like the runtimeConfig is not working as expected, since there are no changes on dev-server start.
> 
> Did you comment out the disable instrumentation env var in order to test it locally?

Yes but I get interesting errors...
image

Started dev server in app package, commented out the instrumentation thing.

**Comment by qhantom** [comment]
> > > Looks smooth, but I don't see any environment indicator. APP_ENV is set to development, seems to me like the runtimeConfig is not working as expected, since there are no changes on dev-server start.
> > 
> > 
> > Did you comment out the disable instrumentation env var in order to test it locally?
> 
> Yes but I get interesting errors... image
> 
> Started dev server in app package, commented out the instrumentation thing.

Hm I cannot reproduce it. I changed the api url env var, maybe this will help.

**Review by PhilKsr — APPROVED** [review]

**Pull request merged**
