### PR TITLE
499 lib validate existing tests for headertsx

### LINKED ISSUE #499: [lib] validate existing tests for Header.tsx
**Description**
Since the codebase evolved over the last couple of month, we need to validate, whether the tests are still passing and need to be extended.

**Scope**
- [x] update `MIGRATION.md`
- [x] validate existing tests
- [x] create new tests if needed

### PR DESCRIPTION
**Pull request by qhantom**
## DESCRIPTION

This PR updates tests for the `Header.tsx` file. Additionally, I updates the migration guide section of the docs slightly to provider better DX.

### TO-DO

- [x] implement and update tests
- [x] update docs
- [x] pull `main` & resolve merge conflicts
- [x] check Vercel deployment

### CLOSES

Closes #499

### CODE REVIEW

**Comment by qhantom** [comment]
@PhilKsr I don't get it why it includes the changes from the "add migration guide to docs" PR since it's already on `main` and has been reviewed bei Cathrin 🤔 I did a rebase but I should recognise that only the diff to `main` is relevant here.

**Comment by PhilKsr** [comment]
> * ment and update tests
> * [x]  update docs
> * [x]  pull `main` & resolve merge conflicts

Yes thats weird! I skipped all changes outside of the Header component and test-component, is that correct?

**Review by PhilKsr — APPROVED** [review]

**Comment by qhantom** [comment]
> > * ment and update tests
> > * [x]   update docs
> > * [x]   pull `main` & resolve merge conflicts
> 
> Yes thats weird! I skipped all changes outside of the Header component and test-component, is that correct?



> > * ment and update tests
> > * [x]   update docs
> > * [x]   pull `main` & resolve merge conflicts
> 
> Yes thats weird! I skipped all changes outside of the Header component and test-component, is that correct?

And the `UserMenu.tsx` and `SearchBar.tsx` are relevant 🙂 Just give a ping if you reviewed them.

**Comment by PhilKsr** [comment]
> > Yes thats weird! I skipped all changes outside of the Header component and test-component, is that correct?
> 
> And the `UserMenu.tsx` and `SearchBar.tsx` are relevant 🙂 Just give me a ping if you reviewed them.

Ping! Works like a charm!

**Comment by qhantom** [comment]
@PhilKsr I made some changes due to the Mantine upgrade, could you please review them again?

**Pull request merged**
