### PR TITLE
Refactor Translation Page 

### LINKED ISSUE #648: Refactor Translation Page
**Description**
The Translation page needs to be refactored to include a table with filtering functionality. Users should be able to edit the translations in both German and English.

**Scope**
Implementing a table with filtering options, along with the ability for users to edit translations directly.

- [x] implement changes
  - [x] Create a table for the translations
  - [x] Implement filtering
  - [x] Enable active editing of German and English translations

- [x] update `MIGRATION.md`
- [ ] update docs

### PR DESCRIPTION
**Pull request by CathrinTruchan**
## DESCRIPTION

The Translation Page is refactored: 

- The TableComponent is now used instead of the jsonTree
- The functionality to update translations has been fixed
- The functionality to reset translations has been fixed

### TO-DO

- [X] pull `main` & resolve merge conflicts
- [X] check Vercel deployment

### CLOSES

closes #648

### CODE REVIEW

**Review by qhantom — COMMENTED** [review]
Code looks good! As I was testing, I tried to figure out how to edit a translation value until I realised I need to click in the word. Maybe we can highlight the input field a bit more to suggest an editable field, what do you think @CathrinTruchan?

image

**Comment by CathrinTruchan** [comment]
> Code looks good! As I was testing, I tried to figure out how to edit a translation value until I realised I need to click in the word. Maybe we can highlight the input field a bit more to suggest an editable field, what do you think @CathrinTruchan?
> 
> image

Sure! Good idea!

**Comment by CathrinTruchan** [comment]
@qhantom Which do you like better? 
A subtle bottom border or a proper input field? 

Screenshot 2024-12-09 at 09 07 07


Screenshot 2024-12-09 at 09 07 50

**Comment by qhantom** [comment]
> @qhantom Which do you like better? A subtle bottom border or a proper input field?

I like the subtle bottom border more 🙂

**Comment by CathrinTruchan** [comment]
> > @qhantom Which do you like better? A subtle bottom border or a proper input field?
> 
> I like the subtle bottom border more 🙂

You can have another look 👀

**Comment by qhantom** [comment]
> > > @qhantom Which do you like better? A subtle bottom border or a proper input field?
> > 
> > 
> > I like the subtle bottom border more 🙂
> 
> You can have another look 👀

Nice one, thanks! Another suggestion: could you make the whole row clickable instead of just the arrows?

**Comment by CathrinTruchan** [comment]
> > > > @qhantom Which do you like better? A subtle bottom border or a proper input field?
> > > 
> > > 
> > > I like the subtle bottom border more 🙂
> > 
> > 
> > You can have another look 👀
> 
> Nice one, thanks! Another suggestion: could you make the whole row clickable instead of just the arrows?

Good point 🎾 
The whole row is now clickable.

**Review by qhantom — APPROVED** [review]

**Comment by qhantom** [comment]
@CathrinTruchan I'm gonna merge this since it's approved 👍

**Comment by CathrinTruchan** [comment]
> @CathrinTruchan I'm gonna merge this since it's approved 👍

thanks for merging 🙏

**Pull request merged**
