### PR TITLE
feat: enable props forwarding for appshell mantine components

### PR DESCRIPTION
**Pull request by qhantom**
## DESCRIPTION

This PR enables the ability to pass all Mantine props to our custom components that forward them to the Mantine components. The win here is much higher customizability.

### TO-DO

- [x] implement and update tests
- [x] update docs
- [x] pull `main` & resolve merge conflicts
- [x] check Vercel deployment

### CODE REVIEW

**Review by PhilKsr — APPROVED** [review]
Looks good! I think we should implement this in all lib-components. For example the table could be more flexible. What do you think? New ticket?

**Comment by qhantom** [comment]
> Looks good! I think we should implement this in all lib-components. For example the table could be more flexible. What do you think? New ticket?

Good point, let me implement it in this PR since it shouldn't take too long.

**Comment by qhantom** [comment]
@PhilKsr It was indeed only the table component that was missing props forwarding. Please have another look 🙂

**Comment by PhilKsr** [comment]
> @PhilKsr It was indeed only the table component that was missing props forwarding. Please have another look 🙂

Funny xD

**Review by PhilKsr — APPROVED** [review]

**Pull request merged**
