### PR TITLE
Fix corrupt lib v3

### LINKED ISSUE #435: Fix corrupt lib v3
Currently, the lib v3 is not working properly due to heavy refactoring in the past and unexpected failures. This needs to be fixed and released as a new major version v4.

### PR DESCRIPTION
**Pull request by qhantom**
**DESCRIPTION**
 
This PR contains major architectural changes. We decided on moving generic logic / components into the `lib` package and specific logic / components into the `app` package. Projects based on Essencium Frontend use the `app` as starting point which consumes the generic components from the `lib`. If a project needs more specific logic for an imported component, it's possible to just copy the component from the `lib`, paste it into the Essencium Fronted based application and customise it as needed.

The Vercel deployment has succeeded. Unfortunately, we - of course - have many merge conflicts. I already included all changes from the last version 2 and the last version 3 so that we confidentially can force push this PR.

To test the major changes, please do the following:

1. check out the branch `rollback-2-4-0`
2. make a clean install of the monorepo (execute `pnpm clean:install` on root level)
3. start the dev server and check, if you get any warnings or even errors

The merge of this PR will trigger a major version update of all packages (initiated through the commit prefix `refactor!`).
 
**CLOSES**
 
Closes #435

### CODE REVIEW

**Comment by CathrinTruchan** [comment]
@qhantom: I checked out the branch as described and tested the app. Everything looks good so far and works as expected. No warnings or errors. I also looked through the files and changes and haven't noticed anything unusual.

**Comment by qhantom** [comment]
> @qhantom: I checked out the branch as described and tested the app. Everything looks good so far and works as expected. No warnings or errors. I also looked through the files and changes and haven't noticed anything unusual.

Cool, thanks a lot 🙏

**Review by PhilKsr — APPROVED** [review]
Works like a charm and code looks good! Thanks for your work @qhantom!

**Comment by qhantom** [comment]
> Works like a charm and code looks good! Thanks for your work @qhantom!

Nice, thanks for reviewing 🚀

**Review by CathrinTruchan — APPROVED** [review]

**Pull request merged**
